# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0004_auto_20190614_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_locale',
            field=models.ImageField(default='/home/karangu/Desktop/Gallery/media', upload_to='images/'),
        ),
    ]
